name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
      - name: Bump version
        env:
          REF: ${{ github.ref }}
        run: |
          sed -i "s/pluginVersion=SNAPSHOT/pluginVersion=${REF:11}/" gradle.properties
      - name: Create release with Gradle
        run: ./gradlew clean build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            spigot/build/libs/*-all.jar